version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
      timezone: "Europe/London"
    labels:
      - "npm dependencies"
    versioning-strategy: widen
    open-pull-requests-limit: 10
    assignees:
      - "AffirmedVisionary"
