name: Lint Checker
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      # ESLint and Prettier must be in `package.json`
      - name: Install Node.js dependencies
        run: rm -rf node_modules && yarn install --frozen-lockfile

      - run: npm update && popd

      - name: Run linters
        uses: wearerequired/lint-action@v1.9.0
        with:
          eslint: true
          eslint_extensions: js
