name: Lint Checker
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - name: Run linters
        uses: wearerequired/lint-action@v1.9.0
        with:
          eslint: true
          eslint_extensions: js
