import { Image } from '@chakra-ui/image'
import { Box, Container, Divider } from '@chakra-ui/layout'
import Head from 'next/head'
import React from 'react'
import WithSubnavigation from './menu'


const Layout = ({children, title = 'Lawfully White Construction Ltd'}) => {
  return (
    <Container maxW="container.xl">
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <WithSubnavigation />
      </header>
      <Box>
      {children}
      </Box>
      <Divider />
      <footer>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className='logo'>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </Container>
  )
}

export default Layout
