import { Image } from '@chakra-ui/image'
import {
  Box,
  Container,
  Divider,
  Heading,
  Link,
  Stack,
  Text,
} from '@chakra-ui/layout'
import { useColorModeValue } from '@chakra-ui/color-mode'
import Head from 'next/head'
import React from 'react'
import WithSubnavigation from './menu'
import LargeWithNewsletter from './footer'
import { useRouter } from 'next/router'

const Layout = ({
  children,
  title = 'Lawfully White Construction Ltd',
  heroImg = 'https://res.cloudinary.com/charlenegrant/image/upload/v1619918838/lawfullywhite-assets/tools-middle_m9egrh.png',
  heroHeading,
  heroIntro = 'Making Dream Spaces come to fruition',
  heroButtons = [
    {
      id: 1,
      label: 'Get In Touch',
      href: '/contact',
    },
    {
      id: 2,
      label: 'About Us',
      href: '/about',
    },
  ],
}) => {
  const heroTitle = heroHeading || title
  return (
    <Container maxW='container.xl'>
      <Head>
        <title>{title} || Lawfully White Construction Ltd</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <header>
      <WithSubnavigation />

        <Box
                  pos='relative'
                  overflow='hidden'
                  backgroundImage={`url(${heroImg})`}
                  bgPos='center'
          bgSize='cover'
        >
            <Box
        >

          {/* <AspectRatio maxW="1440" ratio={3 / 2}>
  <iframe
    title="naruto"
    src={require('../../public/yellow-crane.mp4')}
  />
</AspectRatio> */}

          <Box maxW='7xl' mx='auto'>
            <Box
              pos='relative'
              pb={{ base: 8, sm: 16, md: 20, lg: 28, xl: 32 }}
              w='full'
              border='solid 1px transparent'
            >
              <Box
                mt={{ base: 10 }}
                mx='auto'
                maxW={{ base: '7xl' }}
                px={{ base: 4, sm: 6, lg: 8 }}
                pt={{ base: 12, md: 16, lg: 20, xl: 28 }}
              >
                <Box
                  textAlign='center'
                  w={{ base: 'full', md: 11 / 12, xl: 8 / 12 }}
                  mx='auto'
                >
                  <Heading
                    as='h1'
                    fontSize={{ base: '4xl', sm: '5xl', md: '6xl' }}
                    letterSpacing='tight'
                    lineHeight='short'
                    fontWeight='extrabold'
                    color={useColorModeValue('black', 'white')}
                  >
                    {heroTitle}
                  </Heading>
                  <Text
                    mt={{ base: 3, sm: 5, md: 5 }}
                    mx={{ sm: 'auto', lg: 0 }}
                    mb={6}
                    fontSize={{ base: 'lg', md: 'xl' }}
                    color={useColorModeValue('black', 'white')}
                    lineHeight='base'
                  >
                    {heroIntro}
                  </Text>
                  <Stack
                    direction={{ base: 'column', sm: 'column', md: 'row' }}
                    mb={{ base: 4, md: 8 }}
                    spacing={{ base: 4, md: 2 }}
                    justifyContent='center'
                  >
                      {heroButtons.map((button) => {
                      const router = useRouter()
                      return (
                        <Box rounded='full' shadow='md' key={button.id}>
                          <Link
                            onClick={() => router.push(`${button.href}`)}
                            w='full'
                            display='flex'
                            alignItems='center'
                            justifyContent='center'
                            border='solid 1px transparent'
                            fontSize={{ base: 'md', md: 'lg' }}
                            rounded='md'
                            color={useColorModeValue('white', 'black')}
                            bg={useColorModeValue('black', 'white')}
                            _hover={{
                              color: useColorModeValue('black', 'white'),
                              bg: useColorModeValue('#ffde59', 'black'),
                            }}
                            px={{ base: 8, md: 10 }}
                            py={{ base: 3, md: 4 }}
                          >
                            {button.label}
                          </Link>
                        </Box>
                      )
                    })}
                  </Stack>
                </Box>
              </Box>
            </Box>
          </Box>
            </Box>
            
          </Box>
      </header>
      <Container Container className='main' maxW={'5xl'} py={12}>{children}</Container>
      <Divider />
    <LargeWithNewsletter />
    </Container>
  )
}

export default Layout
